version: "3"

services:
  app:
    image: python:3
    build:
      context: .
      args:
        VERSION: 3
    working_dir: /usr/src/app
    command: ["bash"]
    volumes:
      - ./bashrc:/root/.bashrc
    apt:
      packages:
        - zip
        - git
